from typing import Callable, Any, Optional

class FastMCP:
    def __init__(self, name: str, **kwargs: Any) -> None: ...
    def tool(self, name: Optional[str] = None, description: Optional[str] = None) -> Callable[[Callable[..., Any]], Callable[..., Any]]: ...
    def run(self) -> None: ...
